controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_front_wheel_joint", "left_rear_wheel_joint"]
      right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]

      wheel_separation: 0.36
      wheel_radius: 0.05

      base_frame_id: base_link
      use_stamped_vel: false
      publish_rate: 50

      enable_odom_tf: true
      odom_frame_id: odom
      pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
      twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]