controller_manager:
  ros__parameters:
    update_rate: 100  # 控制器更新频率 (Hz)
    use_sim_time: true  # 使用仿真时间

    # 定义关节状态广播器
    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true

    # 定义全向驱动控制器
    fishbot_omni_drive_controller:
      type: omni_drive_controller/OmniDriveController

# 四轮全向控制器配置
fishbot_omni_drive_controller:
  ros__parameters:
    front_left_wheel_joint: front_left_wheel_joint
    front_right_wheel_joint: front_right_wheel_joint
    rear_left_wheel_joint: rear_left_wheel_joint
    rear_right_wheel_joint: rear_right_wheel_joint
    wheel_separation: 0.36  # 轮距
    wheel_diameter: 0.1  # 轮子直径
    publish_rate: 50.0  # 发布频率
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 99999.0, 99999.0, 99999.0, 0.03]
